language: php
branches:
  only:
  - master
  - "/^.*[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+.*$/"
php:
- '7.2'
script: phpunit --bootstrap src/stub.php --test-suffix '-test.php,Test.php,.phpt'
  tests
notifications:
  email: false
before_deploy:
- composer phar:install-tools
- composer install --prefer-dist --no-dev --no-interaction
- php box.phar build
deploy:
  provider: releases
  api_key:
    secure: jhBryRAh2+J0kbj7VSyXZXBBLQPJR61YqvcUe8sjM4jS80tGwLA5OD++/jfdX5sCdqFu6wtWyM3gmI+/Lr54pB0HqLzvq/nt3vqF9evkTszH3OV7J000rK2f9m62uRkqBzek7hOqTg/77x4V5oLyQ/cVkL09mUt35eWi+5QGB4zYy2SMzQihtbmwA6EBoyFirUumlK10V+n8zk+QZtwMNK4P8zwLzQ7qdIqprJ0mPnVniYnSS1mn5TXNFgtvQbjbRkipSbvDAKs8vrtLshX7frXOGS2fDJQ5UP1xYRcX/0+KwHbg0/8I4OWSUqZL9+imTDF2wK4IaWDQ/KOOVNjM1MeEp1YVZaB5gcIMvKIlA6BCeuVuJEuuByoOmF+ouin+vDMrDrZQJWx5Ov2IaVRcYEEdVKGSIpKz3W3nmX5KQuGGvluAOk4u3Utg00wJz4WsKFEjoejIIE4knDhCj9hbk+mDbAUjlyuRKMa5AkxJA2JwR5PL7dli2eN9+PhR17vYtbvel8y8vKQrdfkr5BWaUZpHLLihL50J3TL4kSG0TzGu6UOsZLaW5kVbliTf2BSZ/mhfK+rwZsPcdItUxq9gpxAPkDr9qt7ziNd4EBePazAjE8WfbOghea4wOSoN4nPpEhQmuaYUyJoJn6nrYFVSyQO+Syj+U4wpLg2Ccc0bVRA=
  file: simple-blog.phar
  on:
    repo: bhoogter/simple-blog
  skip_cleanup: 'true'
